packages:
    - apps/*
    - packages/*
onlyBuiltDependencies:
    - '@biomejs/biome'
    - '@swc/core'
    - esbuild
catalog:
    '@biomejs/biome': 1.9.4
    '@testing-library/react': 16.2.0
    '@testing-library/dom': 10.4.0
    '@types/react': 19.0.12
    '@types/react-dom': 19.0.4
    '@vitejs/plugin-react-swc': 3.8.1
    '@vitest/coverage-v8': 3.0.9
    globals: 16.0.0
    jsdom: 26.0.0
    react: 19.0.0
    'react-dom': 19.0.0
    typescript: 5.8.2
    vite: 6.2.2
    vitest: 3.0.9
