packages:
    - apps/*
    - packages/*
onlyBuiltDependencies:
    - '@biomejs/biome'
    - '@swc/core'
    - esbuild
catalog:
    '@biomejs/biome': 1.9.4
    '@testing-library/react': 16.3.0
    '@testing-library/dom': 10.4.0
    '@types/react': 19.1.2
    '@types/react-dom': 19.1.3
    '@vitejs/plugin-react-swc': 3.9.0
    '@vitest/coverage-v8': 3.1.2
    globals: 16.0.0
    jsdom: 26.1.0
    react: 19.1.0
    'react-dom': 19.1.0
    typescript: 5.8.3
    vite: 6.3.4
    vitest: 3.1.2
