services:
    workspace:
        build:
            context: ../
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
        ports:
            - 8080:8080
        command: sleep infinity
